name: CI workflow

on: [push]

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check code style
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.1"
      - run: bash scripts/gofmtcheck.sh
